// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoPlaceOfBirth.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenVASP.ProtocolMessages.Messages {

  /// <summary>Holder for reflection information generated from ProtoPlaceOfBirth.proto</summary>
  public static partial class ProtoPlaceOfBirthReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoPlaceOfBirth.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoPlaceOfBirthReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdQcm90b1BsYWNlT2ZCaXJ0aC5wcm90bxIRcHJvdG9idWZfb3BlbnZhc3Ai",
            "UgoRUHJvdG9QbGFjZU9mQmlydGgSDAoEZGF0ZRgBIAEoCRIVCg1jaXR5X29m",
            "X2JpcnRoGAIgASgJEhgKEGNvdW50cnlfb2ZfYmlydGgYAyABKAlCJaoCIk9w",
            "ZW5WQVNQLlByb3RvY29sTWVzc2FnZXMuTWVzc2FnZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenVASP.ProtocolMessages.Messages.ProtoPlaceOfBirth), global::OpenVASP.ProtocolMessages.Messages.ProtoPlaceOfBirth.Parser, new[]{ "Date", "CityOfBirth", "CountryOfBirth" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtoPlaceOfBirth : pb::IMessage<ProtoPlaceOfBirth> {
    private static readonly pb::MessageParser<ProtoPlaceOfBirth> _parser = new pb::MessageParser<ProtoPlaceOfBirth>(() => new ProtoPlaceOfBirth());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProtoPlaceOfBirth> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenVASP.ProtocolMessages.Messages.ProtoPlaceOfBirthReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoPlaceOfBirth() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoPlaceOfBirth(ProtoPlaceOfBirth other) : this() {
      date_ = other.date_;
      cityOfBirth_ = other.cityOfBirth_;
      countryOfBirth_ = other.countryOfBirth_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoPlaceOfBirth Clone() {
      return new ProtoPlaceOfBirth(this);
    }

    /// <summary>Field number for the "date" field.</summary>
    public const int DateFieldNumber = 1;
    private string date_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Date {
      get { return date_; }
      set {
        date_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "city_of_birth" field.</summary>
    public const int CityOfBirthFieldNumber = 2;
    private string cityOfBirth_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CityOfBirth {
      get { return cityOfBirth_; }
      set {
        cityOfBirth_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "country_of_birth" field.</summary>
    public const int CountryOfBirthFieldNumber = 3;
    private string countryOfBirth_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CountryOfBirth {
      get { return countryOfBirth_; }
      set {
        countryOfBirth_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProtoPlaceOfBirth);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProtoPlaceOfBirth other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Date != other.Date) return false;
      if (CityOfBirth != other.CityOfBirth) return false;
      if (CountryOfBirth != other.CountryOfBirth) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Date.Length != 0) hash ^= Date.GetHashCode();
      if (CityOfBirth.Length != 0) hash ^= CityOfBirth.GetHashCode();
      if (CountryOfBirth.Length != 0) hash ^= CountryOfBirth.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Date.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Date);
      }
      if (CityOfBirth.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CityOfBirth);
      }
      if (CountryOfBirth.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CountryOfBirth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Date.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Date);
      }
      if (CityOfBirth.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CityOfBirth);
      }
      if (CountryOfBirth.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountryOfBirth);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProtoPlaceOfBirth other) {
      if (other == null) {
        return;
      }
      if (other.Date.Length != 0) {
        Date = other.Date;
      }
      if (other.CityOfBirth.Length != 0) {
        CityOfBirth = other.CityOfBirth;
      }
      if (other.CountryOfBirth.Length != 0) {
        CountryOfBirth = other.CountryOfBirth;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Date = input.ReadString();
            break;
          }
          case 18: {
            CityOfBirth = input.ReadString();
            break;
          }
          case 26: {
            CountryOfBirth = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
