// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoTransaction.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenVASP.ProtocolMessages.Messages {

  /// <summary>Holder for reflection information generated from ProtoTransaction.proto</summary>
  public static partial class ProtoTransactionReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoTransaction.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoTransactionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZQcm90b1RyYW5zYWN0aW9uLnByb3RvEhFwcm90b2J1Zl9vcGVudmFzcCJh",
            "ChBQcm90b1RyYW5zYWN0aW9uEhYKDnRyYW5zYWN0aW9uX2lkGAEgASgJEhwK",
            "FHRyYW5zYWN0aW9uX2RhdGV0aW1lGAIgASgJEhcKD3NlbmRpbmdfYWRkcmVz",
            "cxgDIAEoCUIlqgIiT3BlblZBU1AuUHJvdG9jb2xNZXNzYWdlcy5NZXNzYWdl",
            "c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenVASP.ProtocolMessages.Messages.ProtoTransaction), global::OpenVASP.ProtocolMessages.Messages.ProtoTransaction.Parser, new[]{ "TransactionId", "TransactionDatetime", "SendingAddress" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtoTransaction : pb::IMessage<ProtoTransaction> {
    private static readonly pb::MessageParser<ProtoTransaction> _parser = new pb::MessageParser<ProtoTransaction>(() => new ProtoTransaction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProtoTransaction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenVASP.ProtocolMessages.Messages.ProtoTransactionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoTransaction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoTransaction(ProtoTransaction other) : this() {
      transactionId_ = other.transactionId_;
      transactionDatetime_ = other.transactionDatetime_;
      sendingAddress_ = other.sendingAddress_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoTransaction Clone() {
      return new ProtoTransaction(this);
    }

    /// <summary>Field number for the "transaction_id" field.</summary>
    public const int TransactionIdFieldNumber = 1;
    private string transactionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TransactionId {
      get { return transactionId_; }
      set {
        transactionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "transaction_datetime" field.</summary>
    public const int TransactionDatetimeFieldNumber = 2;
    private string transactionDatetime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TransactionDatetime {
      get { return transactionDatetime_; }
      set {
        transactionDatetime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sending_address" field.</summary>
    public const int SendingAddressFieldNumber = 3;
    private string sendingAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SendingAddress {
      get { return sendingAddress_; }
      set {
        sendingAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProtoTransaction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProtoTransaction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TransactionId != other.TransactionId) return false;
      if (TransactionDatetime != other.TransactionDatetime) return false;
      if (SendingAddress != other.SendingAddress) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TransactionId.Length != 0) hash ^= TransactionId.GetHashCode();
      if (TransactionDatetime.Length != 0) hash ^= TransactionDatetime.GetHashCode();
      if (SendingAddress.Length != 0) hash ^= SendingAddress.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TransactionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TransactionId);
      }
      if (TransactionDatetime.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TransactionDatetime);
      }
      if (SendingAddress.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SendingAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TransactionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TransactionId);
      }
      if (TransactionDatetime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TransactionDatetime);
      }
      if (SendingAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SendingAddress);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProtoTransaction other) {
      if (other == null) {
        return;
      }
      if (other.TransactionId.Length != 0) {
        TransactionId = other.TransactionId;
      }
      if (other.TransactionDatetime.Length != 0) {
        TransactionDatetime = other.TransactionDatetime;
      }
      if (other.SendingAddress.Length != 0) {
        SendingAddress = other.SendingAddress;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TransactionId = input.ReadString();
            break;
          }
          case 18: {
            TransactionDatetime = input.ReadString();
            break;
          }
          case 26: {
            SendingAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
