// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoTransferConfirmationMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenVASP.ProtocolMessages.Messages {

  /// <summary>Holder for reflection information generated from ProtoTransferConfirmationMessage.proto</summary>
  public static partial class ProtoTransferConfirmationMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoTransferConfirmationMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoTransferConfirmationMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZQcm90b1RyYW5zZmVyQ29uZmlybWF0aW9uTWVzc2FnZS5wcm90bxIRcHJv",
            "dG9idWZfb3BlbnZhc3AaE1Byb3RvVmFzcEluZm8ucHJvdG8aElByb3RvTWVz",
            "c2FnZS5wcm90bxoVUHJvdG9PcmlnaW5hdG9yLnByb3RvGhZQcm90b0JlbmVm",
            "aWNpYXJ5LnByb3RvGhhQcm90b1RyYW5zZmVyUmVwbHkucHJvdG8aFlByb3Rv",
            "VHJhbnNhY3Rpb24ucHJvdG8i/gIKIFByb3RvVHJhbnNmZXJDb25maXJtYXRp",
            "b25NZXNzYWdlEjAKB21lc3NhZ2UYASABKAsyHy5wcm90b2J1Zl9vcGVudmFz",
            "cC5Qcm90b01lc3NhZ2USNgoKb3JpZ2luYXRvchgCIAEoCzIiLnByb3RvYnVm",
            "X29wZW52YXNwLlByb3RvT3JpZ2luYXRvchI4CgtiZW5lZmljaWFyeRgDIAEo",
            "CzIjLnByb3RvYnVmX29wZW52YXNwLlByb3RvQmVuZWZpY2lhcnkSNwoIdHJh",
            "bnNmZXIYBCABKAsyJS5wcm90b2J1Zl9vcGVudmFzcC5Qcm90b1RyYW5zZmVy",
            "UmVwbHkSOAoLdHJhbnNhY3Rpb24YBSABKAsyIy5wcm90b2J1Zl9vcGVudmFz",
            "cC5Qcm90b1RyYW5zYWN0aW9uEg8KB2NvbW1lbnQYBiABKAkSMgoIVmFzcElu",
            "Zm8YByABKAsyIC5wcm90b2J1Zl9vcGVudmFzcC5Qcm90b1Zhc3BJbmZvQiWq",
            "AiJPcGVuVkFTUC5Qcm90b2NvbE1lc3NhZ2VzLk1lc3NhZ2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::OpenVASP.ProtocolMessages.Messages.ProtoVaspInfoReflection.Descriptor, global::OpenVASP.ProtocolMessages.Messages.ProtoMessageReflection.Descriptor, global::OpenVASP.ProtocolMessages.Messages.ProtoOriginatorReflection.Descriptor, global::OpenVASP.ProtocolMessages.Messages.ProtoBeneficiaryReflection.Descriptor, global::OpenVASP.ProtocolMessages.Messages.ProtoTransferReplyReflection.Descriptor, global::OpenVASP.ProtocolMessages.Messages.ProtoTransactionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenVASP.ProtocolMessages.Messages.ProtoTransferConfirmationMessage), global::OpenVASP.ProtocolMessages.Messages.ProtoTransferConfirmationMessage.Parser, new[]{ "Message", "Originator", "Beneficiary", "Transfer", "Transaction", "Comment", "VaspInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtoTransferConfirmationMessage : pb::IMessage<ProtoTransferConfirmationMessage> {
    private static readonly pb::MessageParser<ProtoTransferConfirmationMessage> _parser = new pb::MessageParser<ProtoTransferConfirmationMessage>(() => new ProtoTransferConfirmationMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProtoTransferConfirmationMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenVASP.ProtocolMessages.Messages.ProtoTransferConfirmationMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoTransferConfirmationMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoTransferConfirmationMessage(ProtoTransferConfirmationMessage other) : this() {
      message_ = other.message_ != null ? other.message_.Clone() : null;
      originator_ = other.originator_ != null ? other.originator_.Clone() : null;
      beneficiary_ = other.beneficiary_ != null ? other.beneficiary_.Clone() : null;
      transfer_ = other.transfer_ != null ? other.transfer_.Clone() : null;
      transaction_ = other.transaction_ != null ? other.transaction_.Clone() : null;
      comment_ = other.comment_;
      vaspInfo_ = other.vaspInfo_ != null ? other.vaspInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProtoTransferConfirmationMessage Clone() {
      return new ProtoTransferConfirmationMessage(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private global::OpenVASP.ProtocolMessages.Messages.ProtoMessage message_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::OpenVASP.ProtocolMessages.Messages.ProtoMessage Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    /// <summary>Field number for the "originator" field.</summary>
    public const int OriginatorFieldNumber = 2;
    private global::OpenVASP.ProtocolMessages.Messages.ProtoOriginator originator_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::OpenVASP.ProtocolMessages.Messages.ProtoOriginator Originator {
      get { return originator_; }
      set {
        originator_ = value;
      }
    }

    /// <summary>Field number for the "beneficiary" field.</summary>
    public const int BeneficiaryFieldNumber = 3;
    private global::OpenVASP.ProtocolMessages.Messages.ProtoBeneficiary beneficiary_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::OpenVASP.ProtocolMessages.Messages.ProtoBeneficiary Beneficiary {
      get { return beneficiary_; }
      set {
        beneficiary_ = value;
      }
    }

    /// <summary>Field number for the "transfer" field.</summary>
    public const int TransferFieldNumber = 4;
    private global::OpenVASP.ProtocolMessages.Messages.ProtoTransferReply transfer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::OpenVASP.ProtocolMessages.Messages.ProtoTransferReply Transfer {
      get { return transfer_; }
      set {
        transfer_ = value;
      }
    }

    /// <summary>Field number for the "transaction" field.</summary>
    public const int TransactionFieldNumber = 5;
    private global::OpenVASP.ProtocolMessages.Messages.ProtoTransaction transaction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::OpenVASP.ProtocolMessages.Messages.ProtoTransaction Transaction {
      get { return transaction_; }
      set {
        transaction_ = value;
      }
    }

    /// <summary>Field number for the "comment" field.</summary>
    public const int CommentFieldNumber = 6;
    private string comment_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Comment {
      get { return comment_; }
      set {
        comment_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "VaspInfo" field.</summary>
    public const int VaspInfoFieldNumber = 7;
    private global::OpenVASP.ProtocolMessages.Messages.ProtoVaspInfo vaspInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::OpenVASP.ProtocolMessages.Messages.ProtoVaspInfo VaspInfo {
      get { return vaspInfo_; }
      set {
        vaspInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProtoTransferConfirmationMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProtoTransferConfirmationMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Message, other.Message)) return false;
      if (!object.Equals(Originator, other.Originator)) return false;
      if (!object.Equals(Beneficiary, other.Beneficiary)) return false;
      if (!object.Equals(Transfer, other.Transfer)) return false;
      if (!object.Equals(Transaction, other.Transaction)) return false;
      if (Comment != other.Comment) return false;
      if (!object.Equals(VaspInfo, other.VaspInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (message_ != null) hash ^= Message.GetHashCode();
      if (originator_ != null) hash ^= Originator.GetHashCode();
      if (beneficiary_ != null) hash ^= Beneficiary.GetHashCode();
      if (transfer_ != null) hash ^= Transfer.GetHashCode();
      if (transaction_ != null) hash ^= Transaction.GetHashCode();
      if (Comment.Length != 0) hash ^= Comment.GetHashCode();
      if (vaspInfo_ != null) hash ^= VaspInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (message_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Message);
      }
      if (originator_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Originator);
      }
      if (beneficiary_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Beneficiary);
      }
      if (transfer_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Transfer);
      }
      if (transaction_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Transaction);
      }
      if (Comment.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Comment);
      }
      if (vaspInfo_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(VaspInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (message_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (originator_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Originator);
      }
      if (beneficiary_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Beneficiary);
      }
      if (transfer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transfer);
      }
      if (transaction_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transaction);
      }
      if (Comment.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Comment);
      }
      if (vaspInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VaspInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProtoTransferConfirmationMessage other) {
      if (other == null) {
        return;
      }
      if (other.message_ != null) {
        if (message_ == null) {
          Message = new global::OpenVASP.ProtocolMessages.Messages.ProtoMessage();
        }
        Message.MergeFrom(other.Message);
      }
      if (other.originator_ != null) {
        if (originator_ == null) {
          Originator = new global::OpenVASP.ProtocolMessages.Messages.ProtoOriginator();
        }
        Originator.MergeFrom(other.Originator);
      }
      if (other.beneficiary_ != null) {
        if (beneficiary_ == null) {
          Beneficiary = new global::OpenVASP.ProtocolMessages.Messages.ProtoBeneficiary();
        }
        Beneficiary.MergeFrom(other.Beneficiary);
      }
      if (other.transfer_ != null) {
        if (transfer_ == null) {
          Transfer = new global::OpenVASP.ProtocolMessages.Messages.ProtoTransferReply();
        }
        Transfer.MergeFrom(other.Transfer);
      }
      if (other.transaction_ != null) {
        if (transaction_ == null) {
          Transaction = new global::OpenVASP.ProtocolMessages.Messages.ProtoTransaction();
        }
        Transaction.MergeFrom(other.Transaction);
      }
      if (other.Comment.Length != 0) {
        Comment = other.Comment;
      }
      if (other.vaspInfo_ != null) {
        if (vaspInfo_ == null) {
          VaspInfo = new global::OpenVASP.ProtocolMessages.Messages.ProtoVaspInfo();
        }
        VaspInfo.MergeFrom(other.VaspInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (message_ == null) {
              Message = new global::OpenVASP.ProtocolMessages.Messages.ProtoMessage();
            }
            input.ReadMessage(Message);
            break;
          }
          case 18: {
            if (originator_ == null) {
              Originator = new global::OpenVASP.ProtocolMessages.Messages.ProtoOriginator();
            }
            input.ReadMessage(Originator);
            break;
          }
          case 26: {
            if (beneficiary_ == null) {
              Beneficiary = new global::OpenVASP.ProtocolMessages.Messages.ProtoBeneficiary();
            }
            input.ReadMessage(Beneficiary);
            break;
          }
          case 34: {
            if (transfer_ == null) {
              Transfer = new global::OpenVASP.ProtocolMessages.Messages.ProtoTransferReply();
            }
            input.ReadMessage(Transfer);
            break;
          }
          case 42: {
            if (transaction_ == null) {
              Transaction = new global::OpenVASP.ProtocolMessages.Messages.ProtoTransaction();
            }
            input.ReadMessage(Transaction);
            break;
          }
          case 50: {
            Comment = input.ReadString();
            break;
          }
          case 58: {
            if (vaspInfo_ == null) {
              VaspInfo = new global::OpenVASP.ProtocolMessages.Messages.ProtoVaspInfo();
            }
            input.ReadMessage(VaspInfo);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
